name: Deploy Vulnerable Application

on:
  push:
    branches:
      - master

jobs:
  deploy-heroku:
    name: Deploy Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      # --- Escaneo de Seguridad Est치tica (SAST) ---
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=fbbonnin-cmd_vulnerable-web-app
            -Dsonar.organization=fbbonnin-cmd
            -Dsonar.host.url=https://sonarcloud.io

      - name: Run Snyk to check for vulnerabilities
        # Se restaura a la versi칩n original que funcionaba correctamente
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=package.json
          fail-on-issues: false
        continue-on-error: true

      # --- Construcci칩n de la Imagen y Escaneo de Vulnerabilidades (Trivy) ---
      - name: Build Docker Image
        run: docker build -t vulnerable-web-app .

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'vulnerable-web-app:latest'
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: 0

      # --- Escaneo de Seguridad Din치mico (DAST) ---
      - name: Run Docker Image for ZAP Scan
        run: docker run -d --rm --name webapp -p 8080:3000 vulnerable-web-app

      - name: ZAP Full Scan
        # Usamos un commit hash estable para evitar el error de "action not found"
        uses: zaproxy/action-full-scan@897c8d9c223c3b0387a26f8d166822557e1b59c4
        with:
          target: 'http://localhost:8080'
          zap_scan_type: 'full-scan'
          zap_report_type: 'html'

      - name: Publish ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-Report
          path: zap-report.html

      - name: Stop ZAP Test Container
        if: always()
        run: docker stop webapp

      # --- Despliegue Final en Heroku ---
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "vulnerable-web-app-francisco"
          heroku_email: "fb.bonnin@gmail.com"
          remote_branch: "master"
          usedocker: true
